# Generated by Django 2.0.13 on 2019-02-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunteruser',
            name='date_of_birth',
        ),
    ]
