---

- name: Ensure OpenSSl and libssl are the latest versions
  apt: 
    name:   
      - openssl
      - libssl-dev
      - libssl-doc
    update_cache: '{{ update_apt_cache }}'
    state: latest
  tags: packages

- name: Install base packages
  apt: 
    name:
      - build-essential
      - git
      - python3-dev
      - python3-pip
      - python3-pycurl
      - supervisor
    update_cache: '{{ update_apt_cache }}'
    force: yes 
    state: present
  tags: packages

- name: Install image libaries for Pillow
  apt: 
    name:
      - libjpeg62
      - libjpeg-dev 
      - libfreetype6 
      - libfreetype6-dev 
      - zlib1g-dev
    update_cache: '{{ update_apt_cache }}'
    force: yes 
    state: present
  tags: packages

- name: Install virtualenv
  pip: 
    name: virtualenv
  tags: packages

- name: Install boto
  pip: 
    name: boto
  tags: packages

- include: create_users_and_groups.yml