---

- name: Provision {{ application_name }} with Ansible
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: no
  remote_user: chinoxl
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
    - set_fact:
        ansible_python_interpreter: /usr/bin/python3.6
  
  vars:
    #top level vars
    - application_user: chinoxl
     #for password "from passlib.hash import sha512_crypt; print sha512_crypt.encrypt('your-password')"
    - application_user_password_hash: '$6$rounds=656000$xl6/PdB6nZtEqGpS$srtAmd34xA3Fg6CvIQnT2DOBvJL.DPAiqhlpPzIHMTcqZxeOeN8LsacAoLPQ1psR6R89K6/xyk/9d.0KxOxh/0'
    - application_group: sudo
    - application_name: hunter_profile 
    - update_apt_cache: yes
    #Postgresql
    - db_name: hunter_db
    - db_user:  postgres 
    - db_password:
    - db_host: 
    - postgresql_version: 9.6
    #Web
    - virtualenv_path: '/webapps/{{ application_name }}'
    - git_root: '{{ virtualenv_path }}/{{ application_name }}'
    - django_dir: '{{ git_root }}' #  Location of manage.py
    - application_log_dir: '{{ virtualenv_path }}/logs'
    - requirements_file: '{{ git_root }}/requirements/production.txt'
    #(Web) Gunicorn
    - gunicorn_user: '{{ application_user }}'
    - gunicorn_group: '{{ application_group }}'
    - gunicorn_num_workers: 1
    - gunicorn_max_requests: 0
    #(Web) Django
    - django_settings_file: 'config.settings.production'
    - django_secret_key: '8yll3$$$omye0+0v=tfb--el9&nqlrppgb96b*21p5isc_#s0u'
    - run_django_makemigrations: yes
    - run_django_migrations: yes
    - run_django_collectstatic: yes
    #(Web) Git
    - setup_git_repo: yes
    - git_repo: 'https://github.com/joemash/hunter_profile.git'
    #(Web) Nginx
    - nginx_server_name: localhost
    - nginx_http_port: 80
    - nginx_https_port: 443
    - nginx_access_log_file: "{{ application_log_dir }}/nginx/nginx_access.log"
    - nginx_error_log_file: "{{ application_log_dir }}/nginx/nginx_error.log"
    - nginx_static_dir: "{{ git_root }}/static/"
    - nginx_media_dir: "{{ git_root }}/media/"
    
  roles:
    - postgresql
    - web
